ft(landing page setup): implement design of landing page
Ebunwadi/teamwork-frontend pull request #2
Opened 2022-12-15 06:13 UTC by Ebunwadi

2022-12-15 08:04 UTC, courage173 requested changes
theses are some changes you need to make.
1. Change to use css modules. you can research on how to do that
2. Ensure you deploy on netlify so we can also have a review url for each PR (pull request)
3. have an assets folder where you put images
4. Create an higher order component called a layout where you put in the header and can wrap other components.

2022-12-15 08:04 UTC, courage173 commented on src/pages/Landing-page/LandingPage.js
> +      <Navbar />
This NavBar is going to be in all the routes. adding it just on the landing page might not make sense to add it here. have an higher Order function to wrap them.

2022-12-15 08:04 UTC, courage173 commented on src/components/landing-page-components/Navbar.jsx
> +// import '../../pages/landing-page/navbar.css'
comments

2022-12-15 22:51 UTC, Ebunwadi commented on src/pages/Landing-page/LandingPage.js
> +      <Navbar />
okay boss

2022-12-20 10:48 UTC, courage173 approved these changes
You can merge now

2022-12-20 10:51 UTC, courage173 commented
You have not added the fonts link

2022-12-21 19:43 UTC, merged